### ISSUE TITLE
CastError - Null check operator used on a null value

### ISSUE THREAD

**Issue by larssn** [arsamme/flutter-positioned-tap-detector#1]
```
positioned_tap_detector_2.dart in _TapPositionDetectorState._onLongPressEvent at line 117 within positioned_tap_detector_2
```

It seems `_pendingTap` can be null occasionally when `_onLongPressEvent` is called. Instead of using the bang operator, wouldn't it be better to just use actual null checks?

**Comment by arsamme** [comment]
@larssn 
Hi, As I don't have free time to work on side projects, Would you please solve this and create PR?

**Comment by larssn** [comment]
Same, very busy. If I get time, I'll squeeze in a PR.

**Comment by greensopinion** [comment]
I had the same issue:

```

Null check operator used on a null value
#0      _TapPositionDetectorState._onLongPressEvent (package:positioned_tap_detector_2/positioned_tap_detector_2.dart:117)
#1      PositionedTapController.onLongPress (package:positioned_tap_detector_2/positioned_tap_detector_2.dart:179)
#2      GestureRecognizer.invokeCallback (package:flutter/src/gestures/recognizer.dart:182)
#3      LongPressGestureRecognizer._checkLongPressStart (package:flutter/src/gestures/long_press.dart:423)
#4      LongPressGestureRecognizer.didExceedDeadline (package:flutter/src/gestures/long_press.dart:372)
#5      PrimaryPointerGestureRecognizer.didExceedDeadlineWithEvent (package:flutter/src/gestures/recognizer.dart:501)
#6      PrimaryPointerGestureRecognizer.addAllowedPointer.<anonymous closure> (package:flutter/src/gestures/recognizer.dart:454)
#7      _rootRun (dart:async/zone.dart:1346)
#8      _CustomZone.run (dart:async/zone.dart:1258)
```

The PR above should address it.

**Comment by arsamme** [comment]
@greensopinion Thank you, I've merged your PR and I'll release it on pub soon

**Comment by greensopinion** [comment]
Thank you. When this gets published we will consume it in flutter_map

**Comment by arsamme** [comment]
@greensopinion sorry for updating too late. done. I'll close this issue.
